In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3])
print(array)

[1 2 3]


In [3]:
array.shape

(3,)

In [4]:
array2=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
array2.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
array2.ndim

1

In [6]:
array.dtype.name

'int64'

In [7]:
array2.size

15

In [8]:
type(array2)

numpy.ndarray

In [9]:
array3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
array3.shape

(3, 5)

In [11]:
zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
a=np.linspace(0,10,20)
a

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a+b)

[4 6 8]


In [17]:
print(a-b)

[-2 -2 -2]


In [18]:
print(a*b)

[ 3  8 15]


In [19]:
liste=[1,2,3,4]
array=np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [20]:
array=np.array(liste)
array

array([1, 2, 3, 4])

In [21]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [22]:
b=a
c=a
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [23]:
d=a.copy()
d

array([5, 2, 3])

In [24]:
a[0]=5

In [25]:
d

array([5, 2, 3])

In [26]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
print(a[0])

1


In [28]:
print(a[0:4])

[1 2 3 4]


In [29]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [30]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
print(b[1,1])

7


In [32]:
print(b[:,1])

[2 7]


In [33]:
print(b[1,:])

[ 6  7  8  9 10]


In [34]:
print(b[1,1:4])

[7 8 9]


In [35]:
print(b[-1,:])

[ 6  7  8  9 10]


In [36]:
print(b[:,-1])

[ 5 10]


In [37]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
b=a.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
b.resize(3,3)

In [42]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])